config/routes.rb
Rails.application.routes.draw do
  get 'access/index'

  get 'access/login'
  get 'access/logout'
  get 'access/attempt_login'
  post 'access/attempt_login'
  resources :positions do
    collection { post :import }
  end
  resources :companies do
    collection { post :import }
  end
  resources :contacts do
    collection { post :import }
  end
  resources :clients do
    collection { post :import }
  end
  resources :users

  root 'access#index'

end

app/models/position.rb
class Position < ActiveRecord::Base
     belongs_to :user
     belongs_to :company
     has_many :clients
     belongs_to :contact
     
      filterrific(
      available_filters: [
    :with_area_of_interest,
    :with_status,
    :with_city,
    :with_user_id,
    :with_company_id
  ]
)

  scope :with_area_of_interest, lambda { |area_of_interests|
  where(area_of_interest: [*area_of_interests])
}

 scope :with_status, lambda { |statuss|
  where(status: [*statuss])
}

scope :with_city, lambda { |citys|
  where(city: [*citys])
}

scope :with_user_id, lambda { |user_ids|
  where(user_id: [*user_ids])
}

scope :with_company_id, lambda { |company_ids|
  where(company_id: [*company_ids])
}

def self.options_for_filtered_area
     [
      ['Marketing', 'Marketing'],
      ['Finance', 'Finance'],
      ['Arhcitecture', 'Architecture'],
      ['Consulting', 'Consulting'],
      ['Engineering', 'Engineering'], 
      ['Event Management & PR', 'Event Management & PR'],
      ['Fashion', 'Fashion'], 
      ['General Business', 'General Business'],
      ['Graphic Design', 'Graphic Design'],
      ['Hospitality', 'Hospitality'],
      ['Human Ressoures','Human Ressoures'],
      ['International Business', 'International Business'],
      ['IT & Web', 'IT & Web'], 
      ['Law', 'Law'],
      ['NGO', 'NGO'],
      ['Public Relations', 'Public Relations'],
      ['Sales', 'Sales'],
      ['Interior Design', 'Interior Design'],
      ['Real Estate', 'Real Estate'],
      ['Sport', 'Sport'],
      ['Health', 'Health'],
      ['Education & Training', 'Education & Training'],
      ['Journalism & Media', 'Journalism & Media'],
      ['Film & Video', 'Film & Video'],
      ['Import Export / Logistics', 'Import Export / Logistics'],
      ['Translation', 'Translation'],
      ['Project Management', 'Project Management'],
      ['Art & Culture', 'Art & Culture'],
      ['Green Tech / Renewable Energies', 'Green Tech / Renewable Energies']
     ]
end
    
    def self.options_for_status
    [
      ['Open', 'Open'],
      ['Occupied', 'Occupied'],
      ['Closed', 'Closed'],
    ]
    end
    
def self.options_for_cities
    [
      ['Shanghai', 'Shanghai'],
      ['Beijing', 'Beijing'],
      ['Shenzhen', 'Shenzhen'],
    ]
end

def self.as_csv
  CSV.generate do |csv|
    csv << column_names
    all.each do |item|
      csv << item.attributes.values_at(*column_names)
    end
  end
end

 def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      position_hash = row.to_hash # exclude the price field
      position = Position.where(id: position_hash["id"])

      if position.count == 1
        position.first.update_attributes(position_hash)
      else
        Position.create!(position_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)
  
end

app/controllers/positions_controller.rb
class PositionsController < ApplicationController
  before_action :confirmed_logged_in
  before_action :set_position, only: [:show, :edit, :update, :destroy]

  # GET /positions
  # GET /positions.json
  def index
    @filterrific = initialize_filterrific(
     Position,
      params[:filterrific],
      select_options: {
        with_area_of_interest: Position.options_for_filtered_area,
        with_status: Position.options_for_status,
        with_city: Position.options_for_cities,
        with_user_id: User.options_for_select,
        with_company_id: Company.options_for_select
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @positions = @filterrific.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @positions.as_csv }
    end
  end
  
  def import
    Position.import(params[:file])
    redirect_to root_url, notice: "Positions imported."
  end
  # GET /positions/1
  # GET /positions/1.json
  def show
  end

  # GET /positions/new
  def new
    @position = Position.new
  end

  # GET /positions/1/edit
  def edit
  end

  # POST /positions
  # POST /positions.json
  def create
    @position = Position.new(position_params)

    respond_to do |format|
      if @position.save
        format.html { redirect_to @position, notice: 'Position was successfully created.' }
        format.json { render :show, status: :created, location: @position }
      else
        format.html { render :new }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /positions/1
  # PATCH/PUT /positions/1.json
  def update
    respond_to do |format|
      if @position.update(position_params)
        format.html { redirect_to @position, notice: 'Position was successfully updated.' }
        format.json { render :show, status: :ok, location: @position }
      else
        format.html { render :edit }
        format.json { render json: @position.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /positions/1
  # DELETE /positions/1.json
  def destroy
    @position.destroy
    respond_to do |format|
      format.html { redirect_to positions_url, notice: 'Position was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_position
      @position = Position.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def position_params
      params.require(:position).permit(:name, :area_of_interest, :link, :city, :company_id, :contact_id, :capacity, :allowance, :hiring_opportunity, :description, :requirements, :remarks, :status, :user_id)
    end
end

app/helpers/positions_helper.rb
module PositionsHelper
end

app/views/positions/_form.html.erb
<%= form_for(@position) do |f| %>
  <% if @position.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@position.errors.count, "error") %> prohibited this position from being saved:</h2>

      <ul>
      <% @position.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="internship-data">
  <div class="position-3">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
   <%= f.label :area_of_interest %><br>
    <%= f.select(:area_of_interest, Position.options_for_filtered_area) %>
  </div>
  <div class="field">
    <%= f.label :link %><br>
    <%= f.text_area :link %>
  </div>
  <div class="field">
    <%= f.label :company_id %><br>
    <%= f.select(:company_id, Company.options_for_select) %>
  </div></div>
  
  <div class="position-3">
  <div class="field">
    <%= f.label :city %><br>
    <%= f.select(:city, Position.options_for_cities) %>
  </div>
  
  <div class="field">
    <%= f.label :contact_id %><br>
    <%= f.select(:contact_id, Contact.options_for_select) %>
  </div>  <div class="field">
    <%= f.label :status %><br>
    <%= f.select(:status, Position.options_for_status) %>
  </div></div>
  
    <div class="position-3">
  <div class="field">
    <%= f.label :capacity %><br>
    <%= f.number_field :capacity %>
  </div>
  <div class="field">
    <%= f.label :allowance %><br>
    <%= f.text_field :allowance %>
  </div><div class="field">
    <%= f.label :user_id %><br>
   <%= f.select(:user_id, User.options_for_select) %>
  </div>
   <div class="field">
    <%= f.label :hiring_opportunity %><br>
    <%= f.check_box :hiring_opportunity %>
  </div>
  </div>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.trix_editor :description %>
  </div>
  <div class="field">
    <%= f.label :requirements %><br>
    <%= f.trix_editor :requirements %>
  </div>
  <div class="field">
    <%= f.label :remarks %><br>
    <%= f.trix_editor :remarks %>
  </div>


    <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= f.submit %>
</button>

<% end %>

app/views/positions/_list.html.erb
<div id="filterrific_results">

<div class="count">
    <%= page_entries_info positions %>
</div>
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-default">
    <tr>
      <th>ID</th>
      <th>Name</th>
      <th>Area of interest</th>
      <th>City</th>
      <th>Company</th>
      <th>Contact</th>
      <th>Capacity</th>
      <th>Allowance</th>
      <th>Hiring</th>
      <th>Status</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @positions.each do |position| %>
      <tr>
        <td><%= position.id %></td>
        <td><%= link_to(position.name.truncate(20), position) %></td>
        <td><%= position.area_of_interest %></td>
        <td><%= position.city %></td>
        <td><%= link_to(position.company.name, position.company) %></td>
        <td><%= link_to(position.contact.name, position.contact) %></td>
        <td><%= position.capacity %></td>
        <td><%= position.allowance %></td>
        <td><%= position.hiring_opportunity %></td>
        <td><%= position.status %></td>
        <td><%= position.user.name %></td>
        <td><%= link_to 'Show', position %></td>
        <td><%= link_to 'Edit', edit_position_path(position) %></td>
        <td><%= link_to 'Destroy', position, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Import a CSV File</h3>
  <%= form_tag import_positions_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
      <% end %>
 <%= will_paginate positions %>

 

app/views/positions/edit.html.erb
<h1>Editing Position</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> <%= link_to 'Show', @position %> 
</button>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', positions_path %>
</button>

app/views/positions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Internship Positions</h1>
<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Position', new_position_path %>
</button>
</div>
 <div class="filter-reset">
    <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <%= link_to('Reset filters', reset_filterrific_url,) %>
</button>
  </div>
<%= form_for_filterrific @filterrific do |f| %>
  
  <div id="position-filters">
  <div class="filter">
   Area of Interest
    <%= f.select(
      :with_area_of_interest,
      @filterrific.select_options[:with_area_of_interest],
      { include_blank: '- All -' }
    ) %>
  </div>
   <div class="filter">
   Status
    <%= f.select(
      :with_status,
      @filterrific.select_options[:with_status],
      { include_blank: '- All -' }
    ) %>
  </div>
  <div class="filter">
  City
    <%= f.select(
      :with_city,
      @filterrific.select_options[:with_city],
      { include_blank: '- All -' }
    ) %>
  </div>
  <div class="filter">
  Owner
    <%= f.select(
      :with_user_id,
      @filterrific.select_options[:with_user_id],
      { include_blank: '- All -' }
    ) %>
  </div>
  <div class="filter-company">
  Company
    <%= f.select(
      :with_company_id,
      @filterrific.select_options[:with_company_id],
      { include_blank: '- All -' }
    ) %>
  </div>
  </div>
 
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>


<%= render(
  partial: 'positions/list',
  locals: { positions: @positions }
) %>

app/views/positions/index.js.erb
<% js = escape_javascript(
  render(partial: 'positions/list', locals: { positions: @positions })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/positions/new.html.erb
<h1>New Position</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', positions_path %>
</button>

app/views/positions/show.html.erb
<p id="notice"><%= notice %></p>

<p class="title">
  <strong>Name:</strong>
  <%= @position.name %>
</p>
<table class="table table-striped table-bordered table-hover">
  
<tr><td><strong>Area of interest:</strong></td>
<td><%= @position.area_of_interest %></td></tr>


<tr><td>
  <strong>Link:</strong></td>
  <td><%= link_to @position.link, "http://#{@position.link}" %></td></tr>
</p>

<tr><td>
  <strong>City:</strong></td>
  <td><%= @position.city %></td></tr>
</p>

<tr><td>
  <strong>Company:</strong></td>
  <td><%= link_to(@position.company.name, @position.company) %></td></tr>
</p>

<tr><td>
  <strong>Contact:</strong></td>
  <td><%= link_to(@position.contact.name, @position.contact) %></td></tr>
</p>

<tr><td>
  <strong>Capacity:</strong></td>
  <td><%= @position.capacity %></td></tr>

<tr><td>
  <strong>Allowance:</strong></td>
  <td><%= @position.allowance %></td></tr>

<tr><td>
  <strong>Hiring opportunity:</strong></td>
  <td><%= @position.hiring_opportunity %></td></tr>

<tr><td><strong>Status:</strong></td>
  <td><%= @position.status %></td></tr>

<tr><td><strong>User:</strong></td>
  <td><%= @position.user.name %></td></tr>
</table>
<strong>Description:</strong><br/><br/>
<%= @position.description.html_safe %>
<br/><br/>

<strong>Requirements:</strong><br/><br/>
<%= @position.requirements.html_safe %><br/><br/>


<strong>Remarks:</strong><br/><br/>
<%= @position.remarks.html_safe %>


<br/><br/>
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit Position', edit_position_path(@position) %>
</button>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', positions_path %>
</button>