config/routes.rb
Rails.application.routes.draw do
  get 'access/index'

  get 'access/login'
  get 'access/logout'
  get 'access/attempt_login'
  post 'access/attempt_login'
  resources :positions do
    collection { post :import }
  end
  resources :companies do
    collection { post :import }
  end
  resources :contacts do
    collection { post :import }
  end
  resources :clients do
    collection { post :import }
  end
  resources :users

  root 'access#index'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<p id="notice"><%= notice %></p>
<h4>For entering a new position you must create the company first, then the contact person and finally the position</h4>

<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Company', new_company_path %>
</button>

<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Contact', new_contact_path %>
</button>
</div>

<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Position', new_position_path %>
</button>

<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Client', new_client_path %>
</button>
</div>
</div>
</div>