config/routes.rb
Rails.application.routes.draw do
  get 'access/index'

  get 'access/login'
  get 'access/logout'
  get 'access/attempt_login'
  post 'access/attempt_login'
  resources :positions do
    collection { post :import }
  end
  resources :companies do
    collection { post :import }
  end
  resources :contacts do
    collection { post :import }
  end
  resources :clients do
    collection { post :import }
  end
  resources :users

  root 'access#index'

end

app/models/company.rb
class Company < ActiveRecord::Base
     has_many :contacts
     has_many :clients
    
     filterrific(
      available_filters: [
    :with_area_of_interest,
    :with_status,
    :search_query,
    :sorted_by,
  ]
)
    
  scope :with_area_of_interest, lambda { |area_of_interests|
  where(area_of_interest: [*area_of_interests])
}

 scope :with_status, lambda { |statuss|
  where(status: [*statuss])
}

 scope :search_query, lambda { |query|
  # Searches the students table on the 'first_name' and 'last_name' columns.
  # Matches using LIKE, automatically appends '%' to each term.
  # LIKE is case INsensitive with MySQL, however it is case
  # sensitive with PostGreSQL. To make it work in both worlds,
  # we downcase everything.
  return nil  if query.blank?

  # condition query, parse into individual keywords
  terms = query.downcase.split(/\s+/)

  # replace "*" with "%" for wildcard searches,
  # append '%', remove duplicate '%'s
  terms = terms.map { |e|
    (e.gsub('*', '%') + '%').gsub(/%+/, '%')
  }
  # configure number of OR conditions for provision
  # of interpolation arguments. Adjust this if you
  # change the number of OR conditions.
  num_or_conds = 1
  where(
    terms.map { |term|
      "(LOWER(companies.name) LIKE ?)"
    }.join(' AND '),
    *terms.map { |e| [e] * num_or_conds }.flatten
  )
}
      
    def self.options_for_select
    order('LOWER(name)').map { |e| [e.name, e.id] }
    end
    
    def self.options_for_filtered_area
    [
      ['Marketing', 'Marketing'],
      ['Finance', 'Finance'],
      ['Arhcitecture', 'Architecture'],
      ['Consulting', 'Consulting'],
      ['Engineering', 'Engineering'], 
      ['Event Management & PR', 'Event Management & PR'],
      ['Fashion', 'Fashion'], 
      ['General Business', 'General Business'],
      ['Graphic Design', 'Graphic Design'],
      ['Hospitality', 'Hospitality'],
      ['Human Ressoures','Human Ressoures'],
      ['International Business', 'International Business'],
      ['IT & Web', 'IT & Web'], 
      ['Law', 'Law'],
      ['NGO', 'NGO'],
      ['Public Relations', 'Public Relations'],
      ['Sales', 'Sales'],
      ['Interior Design', 'Interior Design'],
      ['Real Estate', 'Real Estate'],
      ['Sport', 'Sport'],
      ['Health', 'Health'],
      ['Education & Training', 'Education & Training'],
      ['Journalism & Media', 'Journalism & Media'],
      ['Film & Video', 'Film & Video'],
      ['Import Export / Logistics', 'Import Export / Logistics'],
      ['Translation', 'Translation'],
      ['Project Management', 'Project Management'],
      ['Art & Culture', 'Art & Culture'],
      ['Green Tech / Renewable Energies', 'Green Tech / Renewable Energies']
    ]
    end
    
    def self.options_for_status
    [
      ['Partner', 'Partner'],
      ['Lead', 'Lead'],
      ['Closed', 'Closed'],
    ]
    end
    def self.options_for_cities
    [
      ['Shanghai', 'Shanghai'],
      ['Beijing', 'Beijing'],
      ['Shenzhen', 'Shenzhen'],
    ]
    end
    
    def self.as_csv
  CSV.generate do |csv|
    csv << column_names
    all.each do |item|
      csv << item.attributes.values_at(*column_names)
    end
  end
end

     def self.import(file)
    CSV.foreach(file.path, headers: true) do |row|

      company_hash = row.to_hash # exclude the price field
      company = Company.where(id: company_hash["id"])

      if company.count == 1
        company.first.update_attributes(company_hash)
      else
        Company.create!(company_hash)
      end # end if !product.nil?
    end # end CSV.foreach
  end # end self.import(file)
  
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_action :confirmed_logged_in
  before_action :set_company, only: [:show, :edit, :update, :destroy]

  # GET /companies
  # GET /companies.json
  def index
   @filterrific = initialize_filterrific(
     Company,
      params[:filterrific],
      select_options: {
        with_area_of_interest: Company.options_for_filtered_area,
        with_status: Company.options_for_status
      },
      persistence_id: 'shared_key',
      default_filter_params: {},
    ) or return
    # Get an ActiveRecord::Relation for all students that match the filter settings.
    # You can paginate with will_paginate or kaminari.
    # NOTE: filterrific_find returns an ActiveRecord Relation that can be
    # chained with other scopes to further narrow down the scope of the list,
    # e.g., to apply permissions or to hard coded exclude certain types of records.
    @companies = @filterrific.find.page(params[:page])

    # Respond to html for initial page load and to js for AJAX filter updates.
    respond_to do |format|
      format.html
      format.js
      format.csv { send_data @companies.as_csv }
    end
  end

 def import
    Company.import(params[:file])
    redirect_to root_url, notice: "Companies imported."
  end
  
  # GET /companies/1
  # GET /companies/1.json
  def show
  end

  # GET /companies/new
  def new
    @company = Company.new
  end

  # GET /companies/1/edit
  def edit
  end

  # POST /companies
  # POST /companies.json
  def create
    @company = Company.new(company_params)

    respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render :show, status: :created, location: @company }
      else
        format.html { render :new }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /companies/1
  # PATCH/PUT /companies/1.json
  def update
    respond_to do |format|
      if @company.update(company_params)
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { render :show, status: :ok, location: @company }
      else
        format.html { render :edit }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
    @company.destroy
    respond_to do |format|
      format.html { redirect_to companies_url, notice: 'Company was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company
      @company = Company.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_params
      params.require(:company).permit(:name, :area_of_interest, :description, :status, :website, :city, :notes, :adress)
    end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_form.html.erb
<%= form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</h2>

      <ul>
      <% @company.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="internship-data">
  <div class="position-3">
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :area_of_interest %><br>
    <%= f.select(:area_of_interest, Company.options_for_filtered_area) %>
  </div>
  
  <div class="field">
    <%= f.label :status %><br>
     <%= f.select(:status, Company.options_for_status) %>
  </div></div>
    <div class="position-3">
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_area :website %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
       <%= f.select(:city, Company.options_for_cities) %>
  </div>
  <div class="field">
    <%= f.label :notes %><br>
    <%= f.text_area :notes %>
  </div></div>
  <div class="field">
    <%= f.label :adress %><br>
    <%= f.text_area :adress %>
  </div></div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.trix_editor :description %>
  </div>
  <div class="actions">
        <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= f.submit %>
</button>
  </div>
<% end %>

app/views/companies/_list.html.erb
<div id="filterrific_results">

<div class="count">
    <%= page_entries_info companies %>
</div>

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-default">
    <tr>
      <th>Name</th>
      <th>Area of interest</th>
      <th>Status</th>
      <th>Website</th>
      <th>City</th>
      <th>Adress</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @companies.each do |company| %>
      <tr>
        <td><%= link_to(company.name, company) %></td>
        <td><%= company.area_of_interest %></td>
        <td><%= company.status %></td>
        <td><%= link_to company.website, "http://#{company.website}" %></td>
        <td><%= company.city %></td>
        <td><%= company.adress %></td>
        <td><%= link_to 'Show', company %></td>
        <td><%= link_to 'Edit', edit_company_path(company) %></td>
        <td><%= link_to 'Destroy', company, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h3>Import a CSV File</h3>
  <%= form_tag import_companies_path, multipart: true do %>
    <%= file_field_tag :file %>
    <%= submit_tag "Import CSV" %>
      <% end %>
<%= will_paginate companies %>

app/views/companies/edit.html.erb
<h1>Editing Company</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-eye-open" aria-hidden="true"></span> <%= link_to 'Show', @company %> 
</button>


<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', companies_path %>
</button>

app/views/companies/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Companies</h1>
<div class="new-object">
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-plus" aria-hidden="true"></span> <%= link_to 'New Company', new_company_path %>
</button>
</div>
 <div class="filter-reset">
    <button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-remove" aria-hidden="true"></span> <%= link_to('Reset filters', reset_filterrific_url,) %>
</button>
  </div>

<%= form_for_filterrific @filterrific do |f| %>
 <div id="position-filters">
 <div class="filter">
    Search Company Name
    <%# give the search field the 'filterrific-periodically-observed' class for live updates %>
    <%= f.text_field(
      :search_query,
      class: 'filterrific-periodically-observed'
    ) %>
  </div>
 <div class="filter">
   Area of Interest
    <%= f.select(
      :with_area_of_interest,
      @filterrific.select_options[:with_area_of_interest],
      { include_blank: '- All -' }
    ) %>
  </div>
   <div class="filter">
   Status
    <%= f.select(
      :with_status,
      @filterrific.select_options[:with_status],
      { include_blank: '- All -' }
    ) %>
  </div>
  </div>
  <%# add an automated spinner to your form when the list is refreshed %>
  <%= render_filterrific_spinner %>
<% end %>


<%= render(
  partial: 'companies/list',
  locals: { companies: @companies }
) %>

app/views/companies/index.js.erb
<% js = escape_javascript(
  render(partial: 'companies/list', locals: { companies: @companies })
) %>
$("#filterrific_results").html("<%= js %>");

app/views/companies/new.html.erb
<h1>New Company</h1>

<%= render 'form' %>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', companies_path %>
</button>

app/views/companies/show.html.erb
<p id="notice"><%= notice %></p>

<p class="title">
  <strong>Name:</strong>
  <%= @company.name %>
</p>
<table class="table table-striped table-bordered table-hover">
<p>
  <tr><td><strong>Area of interest:</strong></td>
  <td><%= @company.area_of_interest %></td></tr>
</p>



<p>
  <tr><td><strong>Status:</strong></td>
  <td><%= @company.status %></td></tr>
</p>

<p>
  <tr><td><strong>Website:</strong></td>
  <td><%= link_to @company.website, "http://#{@company.website}" %></td></tr>
</p>

<p>
  <tr><td><strong>City:</strong></td>
  <td><%= @company.city %></td></tr>
</p>

<p>
  <tr><td><strong>Notes:</strong></td>
  <td><%= @company.notes %></td></tr>
</p>

<p>
  <tr><td><strong>Adress:</strong></td>
  <td><%= @company.adress %></td></tr>
</p>
</table>
<p>
  <strong>Description:</strong>
  <%= @company.description.html_safe %>
</p>


<br/><br/>
<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-pencil" aria-hidden="true"></span> <%= link_to 'Edit', edit_company_path(@company) %> 
</button>

<button type="button" class="btn btn-default btn-lg">
  <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span> <%= link_to 'Back', companies_path %>
</button>